# Generated by Django 5.1.1 on 2024-10-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_review"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "评论", "verbose_name_plural": "评论"},
        ),
    ]
