# Generated by Django 5.1.1 on 2024-11-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "评论", "verbose_name_plural": "评论"},
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="movie",
            new_name="book",
        ),
    ]
